### ISSUE TITLE
播放列表获取视频时长都是0

### ISSUE THREAD

**Issue by Android-xiaoxian** [Yang9102/TsPlayer#1]
直接运行demo，m3u8的视频链接获取不到，MP4的是可以获取到时长的
ControlWrapper类下的获取时长方法没有获取到时长

`public long getDuration() {
        return mPlayerControl.getDuration();
    }`

**Comment by Android-xiaoxian** [comment]
播放MP4视频，拖到进度条后，一直卡在加载转圈状态
日志打印如下
`I/TXCVodVideoView: sendSimpleEvent 2004 playing

D/SuperPlayerView: TXLivePlayer onPlayEvent event: 2014, 缓冲结束

D/SuperPlayerView: TXLivePlayer onPlayEvent event: 2004, 播放开始

I/TXCVodVideoView: seek to 287861

D/Unknow: [tx_dr_api.cpp, txReportDAU, 124]:【DR】DAU report, eventid=1551, errCode=0, token=12b0e33e-cbde-40ac-a84b-3b9de9c30ba8

D/SuperPlayerView: mVodPlayer.getBufferDuration()=287.861

I/TXCVodVideoView: MEDIA_INFO_BUFFERING_START:

I/TXCVodVideoView: sendSimpleEvent 2007 loading start

D/SuperPlayerView: TXLivePlayer onPlayEvent event: 2007, 缓冲开始

V/TXCVodVideoView: seek complete

D/AudioTrack:  pause(sessionID=9849)

D/SuperPlayerView: mVodPlayer.getBufferDuration()=287.861

D/SuperPlayerView: mVodPlayer.getBufferDuration()=287.861

D/SuperPlayerView: mVodPlayer.getBufferDuration()=287.861

D/SuperPlayerView: mVodPlayer.getBufferDuration()=287.861

D/SuperPlayerView: mVodPlayer.getBufferDuration()=287.861

D/SuperPlayerView: mVodPlayer.getBufferDuration()=287.861

D/SuperPlayerView: mVodPlayer.getBufferDuration()=287.861

I/TXCVodVideoView: MEDIA_INFO_BUFFERING_END: eof 0

I/TXCVodVideoView: sendSimpleEvent 2014 loading end

I/TXCVodVideoView: sendSimpleEvent 2004 playing

D/SuperPlayerView: TXLivePlayer onPlayEvent event: 2014, 缓冲结束

D/SuperPlayerView: TXLivePlayer onPlayEvent event: 2004, 播放开始

I/TXCVodVideoView: seek to 287861

D/Unknow: [tx_dr_api.cpp, txReportDAU, 124]:【DR】DAU report, eventid=1551, errCode=0, token=a1277c33-42eb-4336-ad91-44c6fb73c698

D/AudioTrack:  pause(sessionID=9849)

I/TXCVodVideoView: MEDIA_INFO_BUFFERING_START:

I/TXCVodVideoView: sendSimpleEvent 2007 loading start

D/SuperPlayerView: TXLivePlayer onPlayEvent event: 2007, 缓冲开始

V/TXCVodVideoView: seek complete

D/SuperPlayerView: mVodPlayer.getBufferDuration()=287.861

D/SuperPlayerView: mVodPlayer.getBufferDuration()=287.861

D/SuperPlayerView: mVodPlayer.getBufferDuration()=287.861

D/SuperPlayerView: mVodPlayer.getBufferDuration()=287.861

I/TXCVodVideoView: MEDIA_INFO_BUFFERING_END: eof 0

I/TXCVodVideoView: sendSimpleEvent 2014 loading end

I/TXCVodVideoView: sendSimpleEvent 2004 playing

D/SuperPlayerView: TXLivePlayer onPlayEvent event: 2014, 缓冲结束

D/SuperPlayerView: TXLivePlayer onPlayEvent event: 2004, 播放开始

I/TXCVodVideoView: seek to 287861

D/Unknow: [tx_dr_api.cpp, txReportDAU, 124]:【DR】DAU report, eventid=1551, errCode=0, token=2764994a-4046-46c3-826c-5110bde7f903

I/TXCVodVideoView: MEDIA_INFO_BUFFERING_START:

I/TXCVodVideoView: sendSimpleEvent 2007 loading start

V/TXCVodVideoView: seek complete

D/SuperPlayerView: TXLivePlayer onPlayEvent event: 2007, 缓冲开始

D/AudioTrack:  pause(sessionID=9849)

D/SuperPlayerView: mVodPlayer.getBufferDuration()=287.861

D/SuperPlayerView: mVodPlayer.getBufferDuration()=287.861

D/SuperPlayerView: mVodPlayer.getBufferDuration()=287.861

D/SuperPlayerView: mVodPlayer.getBufferDuration()=287.861

D/SuperPlayerView: mVodPlayer.getBufferDuration()=287.861

D/SuperPlayerView: mVodPlayer.getBufferDuration()=287.861

D/SuperPlayerView: mVodPlayer.getBufferDuration()=287.861

I/TXCVodVideoView: MEDIA_INFO_BUFFERING_END: eof 0

I/TXCVodVideoView: sendSimpleEvent 2014 loading end

I/TXCVodVideoView: sendSimpleEvent 2004 playing

D/SuperPlayerView: TXLivePlayer onPlayEvent event: 2014, 缓冲结束

D/SuperPlayerView: TXLivePlayer onPlayEvent event: 2004, 播放开始

I/TXCVodVideoView: seek to 287861

D/Unknow: [tx_dr_api.cpp, txReportDAU, 124]:【DR】DAU report, eventid=1551, errCode=0, token=2741fc07-37ab-48da-b4f2-0a5da75c0276

D/AudioTrack:  pause(sessionID=9849)

I/TXCVodVideoView: MEDIA_INFO_BUFFERING_START:

I/TXCVodVideoView: sendSimpleEvent 2007 loading start

V/TXCVodVideoView: seek complete

D/SuperPlayerView: TXLivePlayer onPlayEvent event: 2007, 缓冲开始

D/SuperPlayerView: mVodPlayer.getBufferDuration()=287.861

D/SuperPlayerView: mVodPlayer.getBufferDuration()=287.861

D/IJKMEDIA: audio accurate_seek start, is->seek_pos=287861000, audio_clock=287.530667, is->accurate_seek_start_time = 135666817

D/SuperPlayerView: mVodPlayer.getBufferDuration()=287.861

D/IJKMEDIA: audio accurate_seek is ok, is->drop_aframe_count=8, audio_clock = 287.872000

I/TXCVodVideoView: MEDIA_INFO_BUFFERING_END: eof 0

I/TXCVodVideoView: sendSimpleEvent 2014 loading end

I/TXCVodVideoView: sendSimpleEvent 2004 playing

D/SuperPlayerView: TXLivePlayer onPlayEvent event: 2014, 缓冲结束

D/SuperPlayerView: TXLivePlayer onPlayEvent event: 2004, 播放开始

I/TXCVodVideoView: seek to 287861

D/Unknow: [tx_dr_api.cpp, txReportDAU, 124]:【DR】DAU report, eventid=1551, errCode=0, token=6c0e3791-ef9a-40b2-bdcf-3ebc54d1b397

D/AudioTrack:  pause(sessionID=9849)

I/TXCVodVideoView: MEDIA_INFO_BUFFERING_START:

I/TXCVodVideoView: sendSimpleEvent 2007 loading start

V/TXCVodVideoView: seek complete

D/SuperPlayerView: TXLivePlayer onPlayEvent event: 2007, 缓冲开始

D/SuperPlayerView: mVodPlayer.getBufferDuration()=287.861

D/SuperPlayerView: mVodPlayer.getBufferDuration()=287.861

D/SuperPlayerView: mVodPlayer.getBufferDuration()=287.861

D/SuperPlayerView: mVodPlayer.getBufferDuration()=287.861

I/TXCVodVideoView: MEDIA_INFO_BUFFERING_END: eof 0

I/TXCVodVideoView: sendSimpleEvent 2014 loading end

I/TXCVodVideoView: sendSimpleEvent 2004 playing

D/SuperPlayerView: TXLivePlayer onPlayEvent event: 2014, 缓冲结束

D/SuperPlayerView: TXLivePlayer onPlayEvent event: 2004, 播放开始

I/TXCVodVideoView: seek to 287861

D/Unknow: [tx_dr_api.cpp, txReportDAU, 124]:【DR】DAU report, eventid=1551, errCode=0, token=ede159aa-b21f-4b11-86fa-38411fb1f36a

I/TXCVodVideoView: MEDIA_INFO_BUFFERING_START:

I/TXCVodVideoView: sendSimpleEvent 2007 loading start

V/TXCVodVideoView: seek complete

D/SuperPlayerView: TXLivePlayer onPlayEvent event: 2007, 缓冲开始

D/SuperPlayerView: mVodPlayer.getBufferDuration()=287.861

D/AudioTrack:  pause(sessionID=9849)

D/SuperPlayerView: mVodPlayer.getBufferDuration()=287.861

D/SuperPlayerView: mVodPlayer.getBufferDuration()=287.861

I/TXCVodVideoView: MEDIA_INFO_BUFFERING_END: eof 0

I/TXCVodVideoView: sendSimpleEvent 2014 loading end

I/TXCVodVideoView: sendSimpleEvent 2004 playing

D/SuperPlayerView: TXLivePlayer onPlayEvent event: 2014, 缓冲结束

D/SuperPlayerView: TXLivePlayer onPlayEvent event: 2004, 播放开始

I/TXCVodVideoView: seek to 287861

D/Unknow: [tx_dr_api.cpp, txReportDAU, 124]:【DR】DAU report, eventid=1551, errCode=0, token=8dedf5d3-1705-402d-9720-4ea90749f459

D/SuperPlayerView: mVodPlayer.getBufferDuration()=293.099

I/TXCVodVideoView: MEDIA_INFO_BUFFERING_START:

I/TXCVodVideoView: sendSimpleEvent 2007 loading start

V/TXCVodVideoView: seek complete

D/SuperPlayerView: TXLivePlayer onPlayEvent event: 2007, 缓冲开始

D/AudioTrack:  pause(sessionID=9849)

D/SuperPlayerView: mVodPlayer.getBufferDuration()=287.861

D/SuperPlayerView: mVodPlayer.getBufferDuration()=287.861

D/SuperPlayerView: mVodPlayer.getBufferDuration()=287.861

I/TXCVodVideoView: MEDIA_INFO_BUFFERING_END: eof 0

I/TXCVodVideoView: sendSimpleEvent 2014 loading end

I/TXCVodVideoView: sendSimpleEvent 2004 playing

D/SuperPlayerView: TXLivePlayer onPlayEvent event: 2014, 缓冲结束

D/SuperPlayerView: TXLivePlayer onPlayEvent event: 2004, 播放开始

I/TXCVodVideoView: seek to 287861`

**Comment by ejtour** [comment]
> 播放MP4视频，拖到进度条后，一直卡在加载转圈状态
> 日志打印如下
> `I/TXCVodVideoView: sendSimpleEvent 2004 playing
> 
> D/SuperPlayerView: TXLivePlayer onPlayEvent event: 2014, 缓冲结束
> 
> D/SuperPlayerView: TXLivePlayer onPlayEvent event: 2004, 播放开始
> 
> I/TXCVodVideoView: seek to 287861
> 
> D/Unknow: [tx_dr_api.cpp, txReportDAU, 124]:【DR】DAU report, eventid=1551, errCode=0, token=12b0e33e-cbde-40ac-a84b-3b9de9c30ba8
> 
> D/SuperPlayerView: mVodPlayer.getBufferDuration()=287.861
> 
> I/TXCVodVideoView: MEDIA_INFO_BUFFERING_START:
> 
> I/TXCVodVideoView: sendSimpleEvent 2007 loading start
> 
> D/SuperPlayerView: TXLivePlayer onPlayEvent event: 2007, 缓冲开始
> 
> V/TXCVodVideoView: seek complete
> 
> D/AudioTrack: pause(sessionID=9849)
> 
> D/SuperPlayerView: mVodPlayer.getBufferDuration()=287.861
> 
> D/SuperPlayerView: mVodPlayer.getBufferDuration()=287.861
> 
> D/SuperPlayerView: mVodPlayer.getBufferDuration()=287.861
> 
> D/SuperPlayerView: mVodPlayer.getBufferDuration()=287.861
> 
> D/SuperPlayerView: mVodPlayer.getBufferDuration()=287.861
> 
> D/SuperPlayerView: mVodPlayer.getBufferDuration()=287.861
> 
> D/SuperPlayerView: mVodPlayer.getBufferDuration()=287.861
> 
> I/TXCVodVideoView: MEDIA_INFO_BUFFERING_END: eof 0
> 
> I/TXCVodVideoView: sendSimpleEvent 2014 loading end
> 
> I/TXCVodVideoView: sendSimpleEvent 2004 playing
> 
> D/SuperPlayerView: TXLivePlayer onPlayEvent event: 2014, 缓冲结束
> 
> D/SuperPlayerView: TXLivePlayer onPlayEvent event: 2004, 播放开始
> 
> I/TXCVodVideoView: seek to 287861
> 
> D/Unknow: [tx_dr_api.cpp, txReportDAU, 124]:【DR】DAU report, eventid=1551, errCode=0, token=a1277c33-42eb-4336-ad91-44c6fb73c698
> 
> D/AudioTrack: pause(sessionID=9849)
> 
> I/TXCVodVideoView: MEDIA_INFO_BUFFERING_START:
> 
> I/TXCVodVideoView: sendSimpleEvent 2007 loading start
> 
> D/SuperPlayerView: TXLivePlayer onPlayEvent event: 2007, 缓冲开始
> 
> V/TXCVodVideoView: seek complete
> 
> D/SuperPlayerView: mVodPlayer.getBufferDuration()=287.861
> 
> D/SuperPlayerView: mVodPlayer.getBufferDuration()=287.861
> 
> D/SuperPlayerView: mVodPlayer.getBufferDuration()=287.861
> 
> D/SuperPlayerView: mVodPlayer.getBufferDuration()=287.861
> 
> I/TXCVodVideoView: MEDIA_INFO_BUFFERING_END: eof 0
> 
> I/TXCVodVideoView: sendSimpleEvent 2014 loading end
> 
> I/TXCVodVideoView: sendSimpleEvent 2004 playing
> 
> D/SuperPlayerView: TXLivePlayer onPlayEvent event: 2014, 缓冲结束
> 
> D/SuperPlayerView: TXLivePlayer onPlayEvent event: 2004, 播放开始
> 
> I/TXCVodVideoView: seek to 287861
> 
> D/Unknow: [tx_dr_api.cpp, txReportDAU, 124]:【DR】DAU report, eventid=1551, errCode=0, token=2764994a-4046-46c3-826c-5110bde7f903
> 
> I/TXCVodVideoView: MEDIA_INFO_BUFFERING_START:
> 
> I/TXCVodVideoView: sendSimpleEvent 2007 loading start
> 
> V/TXCVodVideoView: seek complete
> 
> D/SuperPlayerView: TXLivePlayer onPlayEvent event: 2007, 缓冲开始
> 
> D/AudioTrack: pause(sessionID=9849)
> 
> D/SuperPlayerView: mVodPlayer.getBufferDuration()=287.861
> 
> D/SuperPlayerView: mVodPlayer.getBufferDuration()=287.861
> 
> D/SuperPlayerView: mVodPlayer.getBufferDuration()=287.861
> 
> D/SuperPlayerView: mVodPlayer.getBufferDuration()=287.861
> 
> D/SuperPlayerView: mVodPlayer.getBufferDuration()=287.861
> 
> D/SuperPlayerView: mVodPlayer.getBufferDuration()=287.861
> 
> D/SuperPlayerView: mVodPlayer.getBufferDuration()=287.861
> 
> I/TXCVodVideoView: MEDIA_INFO_BUFFERING_END: eof 0
> 
> I/TXCVodVideoView: sendSimpleEvent 2014 loading end
> 
> I/TXCVodVideoView: sendSimpleEvent 2004 playing
> 
> D/SuperPlayerView: TXLivePlayer onPlayEvent event: 2014, 缓冲结束
> 
> D/SuperPlayerView: TXLivePlayer onPlayEvent event: 2004, 播放开始
> 
> I/TXCVodVideoView: seek to 287861
> 
> D/Unknow: [tx_dr_api.cpp, txReportDAU, 124]:【DR】DAU report, eventid=1551, errCode=0, token=2741fc07-37ab-48da-b4f2-0a5da75c0276
> 
> D/AudioTrack: pause(sessionID=9849)
> 
> I/TXCVodVideoView: MEDIA_INFO_BUFFERING_START:
> 
> I/TXCVodVideoView: sendSimpleEvent 2007 loading start
> 
> V/TXCVodVideoView: seek complete
> 
> D/SuperPlayerView: TXLivePlayer onPlayEvent event: 2007, 缓冲开始
> 
> D/SuperPlayerView: mVodPlayer.getBufferDuration()=287.861
> 
> D/SuperPlayerView: mVodPlayer.getBufferDuration()=287.861
> 
> D/IJKMEDIA: audio accurate_seek start, is->seek_pos=287861000, audio_clock=287.530667, is->accurate_seek_start_time = 135666817
> 
> D/SuperPlayerView: mVodPlayer.getBufferDuration()=287.861
> 
> D/IJKMEDIA: audio accurate_seek is ok, is->drop_aframe_count=8, audio_clock = 287.872000
> 
> I/TXCVodVideoView: MEDIA_INFO_BUFFERING_END: eof 0
> 
> I/TXCVodVideoView: sendSimpleEvent 2014 loading end
> 
> I/TXCVodVideoView: sendSimpleEvent 2004 playing
> 
> D/SuperPlayerView: TXLivePlayer onPlayEvent event: 2014, 缓冲结束
> 
> D/SuperPlayerView: TXLivePlayer onPlayEvent event: 2004, 播放开始
> 
> I/TXCVodVideoView: seek to 287861
> 
> D/Unknow: [tx_dr_api.cpp, txReportDAU, 124]:【DR】DAU report, eventid=1551, errCode=0, token=6c0e3791-ef9a-40b2-bdcf-3ebc54d1b397
> 
> D/AudioTrack: pause(sessionID=9849)
> 
> I/TXCVodVideoView: MEDIA_INFO_BUFFERING_START:
> 
> I/TXCVodVideoView: sendSimpleEvent 2007 loading start
> 
> V/TXCVodVideoView: seek complete
> 
> D/SuperPlayerView: TXLivePlayer onPlayEvent event: 2007, 缓冲开始
> 
> D/SuperPlayerView: mVodPlayer.getBufferDuration()=287.861
> 
> D/SuperPlayerView: mVodPlayer.getBufferDuration()=287.861
> 
> D/SuperPlayerView: mVodPlayer.getBufferDuration()=287.861
> 
> D/SuperPlayerView: mVodPlayer.getBufferDuration()=287.861
> 
> I/TXCVodVideoView: MEDIA_INFO_BUFFERING_END: eof 0
> 
> I/TXCVodVideoView: sendSimpleEvent 2014 loading end
> 
> I/TXCVodVideoView: sendSimpleEvent 2004 playing
> 
> D/SuperPlayerView: TXLivePlayer onPlayEvent event: 2014, 缓冲结束
> 
> D/SuperPlayerView: TXLivePlayer onPlayEvent event: 2004, 播放开始
> 
> I/TXCVodVideoView: seek to 287861
> 
> D/Unknow: [tx_dr_api.cpp, txReportDAU, 124]:【DR】DAU report, eventid=1551, errCode=0, token=ede159aa-b21f-4b11-86fa-38411fb1f36a
> 
> I/TXCVodVideoView: MEDIA_INFO_BUFFERING_START:
> 
> I/TXCVodVideoView: sendSimpleEvent 2007 loading start
> 
> V/TXCVodVideoView: seek complete
> 
> D/SuperPlayerView: TXLivePlayer onPlayEvent event: 2007, 缓冲开始
> 
> D/SuperPlayerView: mVodPlayer.getBufferDuration()=287.861
> 
> D/AudioTrack: pause(sessionID=9849)
> 
> D/SuperPlayerView: mVodPlayer.getBufferDuration()=287.861
> 
> D/SuperPlayerView: mVodPlayer.getBufferDuration()=287.861
> 
> I/TXCVodVideoView: MEDIA_INFO_BUFFERING_END: eof 0
> 
> I/TXCVodVideoView: sendSimpleEvent 2014 loading end
> 
> I/TXCVodVideoView: sendSimpleEvent 2004 playing
> 
> D/SuperPlayerView: TXLivePlayer onPlayEvent event: 2014, 缓冲结束
> 
> D/SuperPlayerView: TXLivePlayer onPlayEvent event: 2004, 播放开始
> 
> I/TXCVodVideoView: seek to 287861
> 
> D/Unknow: [tx_dr_api.cpp, txReportDAU, 124]:【DR】DAU report, eventid=1551, errCode=0, token=8dedf5d3-1705-402d-9720-4ea90749f459
> 
> D/SuperPlayerView: mVodPlayer.getBufferDuration()=293.099
> 
> I/TXCVodVideoView: MEDIA_INFO_BUFFERING_START:
> 
> I/TXCVodVideoView: sendSimpleEvent 2007 loading start
> 
> V/TXCVodVideoView: seek complete
> 
> D/SuperPlayerView: TXLivePlayer onPlayEvent event: 2007, 缓冲开始
> 
> D/AudioTrack: pause(sessionID=9849)
> 
> D/SuperPlayerView: mVodPlayer.getBufferDuration()=287.861
> 
> D/SuperPlayerView: mVodPlayer.getBufferDuration()=287.861
> 
> D/SuperPlayerView: mVodPlayer.getBufferDuration()=287.861
> 
> I/TXCVodVideoView: MEDIA_INFO_BUFFERING_END: eof 0
> 
> I/TXCVodVideoView: sendSimpleEvent 2014 loading end
> 
> I/TXCVodVideoView: sendSimpleEvent 2004 playing
> 
> D/SuperPlayerView: TXLivePlayer onPlayEvent event: 2014, 缓冲结束
> 
> D/SuperPlayerView: TXLivePlayer onPlayEvent event: 2004, 播放开始
> 
> I/TXCVodVideoView: seek to 287861`

已修复
